apiVersion: v1
kind: Secret
metadata:
  name: nexus-secrets
  labels:
    app: nexus-bot
type: Opaque
data:
  # Substitua pelo valor da sua chave Groq em base64 (ex: echo -n "gsk_..." | base64)
  OPEN_ROUTER_KEY: xxxxxpto

