POST http://localhost:11434/api/generate
Content-Type: application/json

{
  "model": "llama2-uncensored:7b",
  "prompt": "Qual é o PIB do Brasil em 2023? O que é o PIB?",
  "stream": false
}

###
POST http://localhost:11434/api/generate
Content-Type: application/json

{
  "model": "tinyllama",
  "prompt": "Qual é o PIB do Brasil em 2023? O que é o PIB?",
  "stream": false
}